### ISSUE TITLE
Make it possible to include route maps without specifying a namespace

### ISSUE THREAD

**Issue by ellmetha** [martenframework/marten#108]
# Description

It is presently possible to define included routes by leveraging the `Marten::Routing::Map#draw` method and by defining a corresponding "path":

```crystal
ARTICLE_ROUTES = Marten::Routing::Map.draw do
  path "", ArticlesHandler, name: "list"
  path "/create", ArticleCreateHandler, name: "create"
  path "/<pk:int>", ArticleDetailHandler, name: "detail"
  path "/<pk:int>/update", ArticleUpdateHandler, name: "update"
  path "/<pk:int>/delete", ArticleDeleteHandler, name: "delete"
end

Marten.routes.draw do
  path "/", HomeHandler, name: "home"
  path "/articles", Articles::ROUTES, name: "articles"
end
```

Defining nested routes like that always requires the definition of an associated `name` for the including route. While this may work fine in some situations, it should be possible to define included routes without having to define a namespace at the including route level (since all the underlying routes must have an associated name):

```crystal
ARTICLE_ROUTES = Marten::Routing::Map.draw do
  path "", ArticlesHandler, name: "article_list"
  path "/create", ArticleCreateHandler, name: "article_create"
  path "/<pk:int>", ArticleDetailHandler, name: "article_detail"
  path "/<pk:int>/update", ArticleUpdateHandler, name: "article_update"
  path "/<pk:int>/delete", ArticleDeleteHandler, name: "article_delete"
end

Marten.routes.draw do
  path "/", HomeHandler, name: "home"
  path "/articles", Articles::ROUTES
end
```

Let's ensure that the use of the `name` argument for including routes is optional when calling the `#path` method. The use of the `name` option should remain mandatory when defining routes for handlers.

**Comment by treagod** [comment]
What do you think about adding an optional namespace paramter to `Marten::Routing::Map.draw`?

Instead of

```ruby
ARTICLE_ROUTES = Marten::Routing::Map.draw do
  path "", ArticlesHandler, name: "article_list"
  path "/create", ArticleCreateHandler, name: "article_create"
  ...
end
# Resulting in /articles [article_list], /articles/create [article_create],...
```

you could do

```ruby
ARTICLE_ROUTES = Marten::Routing::Map.draw(:article) do
  path "", ArticlesHandler, name: "list"
  path "/create", ArticleCreateHandler, name: "create"
  ...
end
# Resulting in /articles [articles:list], /articles/create [article:create],...
```

**Comment by ellmetha** [comment]
Both should be possible I think! 

Not providing a route name when including sub-routes is going to be mostly useful for cases where the individual routes in the sub-routeset are unrelated and do not need to be prefixed by a shared namespace.

Providing a default namespace for sub-routesets is also something that we could do as your examples suggest. 🙂

**Comment by treagod** [comment]
One more thought: when I add the namespace option to `draw`, then there would be 2 ways to define namespaces

```ruby
ARTICLE_ROUTES = Marten::Routing::Map.draw(:article) do
# ...
Marten.routes.draw do
#...
  path "/articles", Articles::ROUTES
end
```

and 

```ruby
ARTICLE_ROUTES = Marten::Routing::Map.draw do
# ...
Marten.routes.draw do
#...
  path "/articles", Articles::ROUTES, name: "article"
end
```

In my opinion there should be only one way to define this, so either remove the name parameter for `path` with a `Map` argument altogether or at least deprecate it.
What's your thought on this?

**Comment by ellmetha** [comment]
> In my opinion there should be only one way to define this, so either remove the name parameter for `path` with a `Map` argument altogether or at least deprecate it.
> 
> Otherwise if we keep both approaches I would at least disallow using both, namespace and name parameter
> 
> What's your thought on this?

I would prefer if we don't remove the ability to specify names for route maps through the use of `#map`. This is the current behavior and I don't think we need to introduce breaking changes and move away from it. I also think that it's more consistent to define all the route names in a similar place (when calling `#path`) versus allowing it in `#draw` too. The other advantage of keeping the `#path` version is that it allows to possibly include the same routes map multiple times with different names if necessary.

If we go with both solutions we could simply validate that included route maps don't have an associated name already if they are targeted by a `#path` call that also specifies a `name` value. What do you think?

**Comment by treagod** [comment]
I think you're right. We shouldn't take the option to rename it, otherwise the developer has to create a new `Map` with the same paths but a different namespace to include it anywhere else.

I'll include the namespace and will write a hint in the documentation, that the name argument has a higher precedence. 

For the namespace I have this use case in mind:

```ruby
ARTICLE_ROUTES = Marten::Routing::Map.draw(:article) do
# ...
end

ADMIN_ROUTES = Marten::Routing::Map.draw do
  path "/articles", ARTICLE_ROUTES
# ...
end

Marten.routes.draw do
#...
  path "/articles", ARTICLE_ROUTES
  path "/admin", ADMIN_ROUTES
end

# Rules: [article:list] [admin:article:list]
# Small advantage: article name doesn't need to be defined twice
# and you have to change it only at the namespace
```

So to be clear I'll:

1. Make `name` optional for calling `#path `with `Map`
2. I'll add a namespace to `self.draw`
3. `name` paremeter will overwrite the namespace defined at `self.draw`
