### ISSUE TITLE
Documentation: Page not found

### ISSUE THREAD

**Issue by treagod** [martenframework/marten#136]
When searching for a topic and following a link I get a page not found.

Steps to reproduce:

1. Navigate to [https://martenframework.com/docs](https://martenframework.com/docs)
2. Click the search input
3. Search for `CSRF`
4. Click on the first result (CSRF protection)
5. You should be on [https://martenframework.com/docs/security/#guides](https://martenframework.com/docs/security/#guides)
6. Click on any of the 4 guides
7. 404

**Workaround:**

Manually click on `Security` in the sidebar. Now all 4 guide links work

**Comment by ellmetha** [comment]
Thanks for reporting this! 🙏 
It should be fixed by a71fd18f38efc3d0c07c87f5ca146f78c4bae9e0.
