### ISSUE TITLE
Allow to explicitly override template loaders

### ISSUE THREAD

**Issue by ellmetha** [martenframework/marten#15]
# Description

Right now, Marten templates are configured through the use of the following configuration options:

```crystal
  config.templates.app_dirs = true
  config.templates.cached = true
  config.templates.dirs = [
    Path["src/templates"],
  ]
```

These configuration options results in the initialization of `Marten::Template::Loader::Base` objects that will allow to load the actual templates at runtime. 

It could be interesting to let users define custom template loader classes that can be configured to be used by Marten at runtime in order to load templates. In order to do so, one option would be to define a `config.templates.loaders` configuration that could be used as follows:

```crystal
  config.templates.loaders = [
    Marten::Template::Loader::AppDirs.new,
    Marten::Template::Loader::FileSystem.new("src/templates"),
    # other loaders... 
  ]
```

When used, the `config.templates.loaders` configuration option would have precedence over all the other options (they would be ignored in this situation).

**Comment by treagod** [comment]
I'm almost done with this addition, but there is on problem: Initialization of `AppDirs` inside the config won't work. The apps can't be discovered here, because of:

```cyrstal
def initialize
  @app_loaders = [] of Loader::FileSystem
  @app_loaders += Marten.apps.app_configs.compact_map(&.templates_loader) # this one
end
```

This should be done during the setup phase of Marten, right? Could we add an optional `#setup` method in the `Base` loader that does nothing, but can be overwritten to do something during the setup phase? So we could configure the loaders after all Marten stuff has been loaded.

**Comment by ellmetha** [comment]
@treagod The simplest solution would probably be to delay the initialization of the app finders in the `Marten::Asset::Finder::AppDirs` class. Instead of initializing the `app_finders` instance variable at initialization time, we could initialize it "lazily" later on when we start making use of the underlying app finders.

For example:

```crystal
class Marten::Asset::Finder::AppDir
  @app_finders : Array(Finder::Base)? = nil

  def initialize
  end

  # [...]

  private

  def app_dirs : Array(Finder::Base)
    @app_finders ||= begin
      app_finders = [] of Finder::Base
      app_finders += Marten.apps.app_configs.compact_map(&.assets_finder)
      app_finders
    end
  end
end
```
