### ISSUE TITLE
Setting a nullable field to `nil` raises exception

### ISSUE THREAD

**Issue by notramo** [martenframework/marten#177]
```crystal
model User < Marten::Model
  # linking GitHub account is not mandatory
  field :github, :string, null: true
end
```

Then updating it like this:
```crystal
user.github = "ellmetha"
user.save!

user.github = nil
user.save!
```

**Comment by ellmetha** [comment]
This is not a bug! Your field defines that nullable values are allowed _at the database level_ by setting the [`null`](https://martenframework.com/docs/models-and-databases/reference/fields#null) option to `true`, but the default value for the [`blank`](https://martenframework.com/docs/models-and-databases/reference/fields#blank) option is still `false` by default. The  [`null`](https://martenframework.com/docs/models-and-databases/reference/fields#null) option defines whether null values are allowed _at the database level_ while the [`blank`](https://martenframework.com/docs/models-and-databases/reference/fields#blank) option defines whether blank values are allowed for model records _at validation time_. If you want to define an optional field, you need to update your field definition to set `null: true` and `blank: true`:

```crystal
model User < Marten::Model
  # linking GitHub account is not mandatory
  field :github, :string, max_size: 255, null: true, blank: true
end
```

**Comment by notramo** [comment]
This is confusing as I thought `blank` only applies to space characters and empty string, not `nil`. That would make sense because it's nullable, and it's set to an empty string, it should be set to null instead, to have only one representation of lack of value. (In most of the cases if the user does not enter value that means no value, with no difference between empty string and `nil` from a UX perspective.)
The documentation should mention that it applies to `nil` also.

**Comment by ellmetha** [comment]
> The documentation should mention that it applies to nil also.

Noted 👍 We can definitely clarify this aspect!
