### ISSUE TITLE
Sign out have to use POST

### ISSUE THREAD

**Issue by notramo** [martenframework/marten#184]
The generated auth app uses GET for signout. This has the following disadvantages.
- An attacker can easily sign out anyone by simply redirecting the user from a malicious site to the sign-out endpoint with a simple HTTP 3xx redirect.
- [Turbo](https://turbo.hotwired.dev) automatically prefetch `<a>` tag `href`s on `mouseenter` event, so when the user moves the mouse over the sign-out button, they are signed out.

I recommend using an empty `<form>` with only a CSRF token, and a `<button>`.

**Comment by notramo** [comment]
Is it possible to have DELETE request with form submits? Does Marten support `_method` field in forms?

**Comment by ellmetha** [comment]
> Does Marten support `_method` field in forms?

It doesn't at the moment but this could be a nice addition to the framework.
