### ISSUE TITLE
Referrer Policy Middleware seems not included in latest release

### ISSUE THREAD

**Issue by GhaniyKie** [martenframework/marten#278]
Hello, i just installed this framework with latest release **0.5.4**, run marten serve, and got this error:

```bash
Showing last frame. Use --error-trace for full trace.

In config/settings/base.cr:16:5

 16 | Marten::Middleware::ReferrerPolicy,
      ^---------------------------------
Error: undefined constant Marten::Middleware::ReferrerPolicy
```

Seems this middleware is not included in latest release:
![image](https://github.com/user-attachments/assets/d0a04b98-05be-4f90-b4d0-13475776124f)

IDK is this the right version, but `Marten::Middleware::ReferrerPolicy` has been included by default on settings.
Current solve i just commented this line and all works fine.

Hope this middleware included in latest release.

Systems:
Crystal v1.14.0; LLVM 18.1.6
Marten v0.5.4
Deepin OS

**Comment by ellmetha** [comment]
Hey! 👋 How was your project generated? The latest release (0.5.4) does not include this middleware and my guess is that you generated your project by using a development version of Marten somehow. Maybe you compiled your Marteb binary from the development branch (`main`) directly?

The following works as expected using the Marten CLI:

```
$ marten -v
Marten 0.5.4
$ marten new my_project && cd my_project
$ shards install
$ marten serve
[I] [2024-12-10 09:25:49 UTC] [Server] Marten running on http://127.0.0.1:8000 (Press CTRL+C to quit)

**Comment by ellmetha** [comment]
Ah I see what's happening. The [instructions for compiling the Marten CLI binary](https://martenframework.com/docs/getting-started/installation#from-the-sources) indicate to clone the main branch (ie. the development branch) of the  repository instead of the v0.5.x branch. That's why you encountered this error. This has been fixed and the documentation will be reflected accordingly. Thanks for letting us know!

**Comment by GhaniyKie** [comment]
Thanks for clarification, @ellmetha. I just installing Marten from previous documentation you were mentioned. Later i'll try to reinstalling and inform you, yaaa...
