### ISSUE TITLE
Add support for JSON model and schema fields

### ISSUE THREAD

**Issue by ellmetha** [martenframework/marten#37]
## Description

It should be possible to define JSON fields as part of models. At the database level, such fields would translate to:

* a `jsonb` column for PostgreSQL
* a `json` column for MySQL
* a `text` column for SQLite

By default, such model fields would simply parse the column string value (unless it's already parsed by the database backend itself) and expose the corresponding `JSON::Any` object:

```crystal
class MyModel < Marten::Model
  field :id, :big_int, primary_key: true, auto: true
  field :data, :json
end

MyModel.last!.data # => JSON::Any object
```

That being said, one of the interesting aspects of JSON strings in Crystal is that they can be used to initialize serializable objects by leveraging the [`JSON::Serializable`](https://crystal-lang.org/api/1.6.1/JSON/Serializable.html) module. In this light, it would be interesting to allow the use of a specific serializable object class in the model field definition and ensure that the parsing of the JSON value results in the initialization of the corresponding objects:

```crystal
class MySerializable
  include JSON::Serializable

  property a : Int32 | Nil
  property b : String | Nil
end

class MyModel < Marten::Model
  field :id, :big_int, primary_key: true, auto: true
  field :data, :json, serializable: MySerializable
end

MyModel.last!.data # => MySerializable object
```

**Comment by pschols** [comment]
Would be awesome to have this.

**Comment by revskill10** [comment]
Would love to have support for `Array` or some `Enumerable`, too.
