### ISSUE TITLE
Add ability to specify unique constraint in Model

### ISSUE THREAD

**Issue by jasonl99** [martenframework/marten#40]
Let me preface this by saying I've just discovered Marten (and love crystal, but don't get to use it much).  Just playing around.  

One thing I've had trouble figuring out is how to add a unique constraint to migrations (other than genmigrations, editing the created migration and adding `add_unique_constraint` manually).  But it seems to me like it might be a good idea to create something in a model's class that does this automatically.

Something like this (ignoring the bad idea of making a full name unique, this is just to illustrate)

```crystal
class Person < Marten::Model
  field :id, :int, primary_key: true, auto: true
  field :first_name, :string, max_size: 50
  field :last_name, :string, max_size: 50
  unique_constraint :full_name, [:first_name, :last_name]
end
```
In this case, the `unique` item would just translate (or be removed from) automatically generated migrations.

There may already be a way to accomplish this, but I have been unable to find it in the docs.

As a full-time rubyist using the Sequel ORM, I absolutely love how you've designed this framework.  Awesome job!!!

**Comment by ellmetha** [comment]
Hey! 👋 

Thanks for the feedback!

Unique constraints are actually already supported in model definitions, but these capabilities are not (yet!) highlighted in the documentation. They can be defined by using the [`#db_unique_constraint`](https://martenframework.com/docs/api/Marten/DB/Model/Table/ClassMethods.html#db_unique_constraint%28name%3AString%7CSymbol%2Cfield_names%3AArray%28String%29%7CArray%28Symbol%29%29%3ANil-instance-method) class method. For example, it is possible to do something like that:

```crystal
class Person < Marten::Model
  field :id, :int, primary_key: true, auto: true
  field :first_name, :string, max_size: 50
  field :last_name, :string, max_size: 50

  db_unique_constraint :author_full_name_constraint, field_names: [:first_name, :last_name]
end
```

And these corresponding unique constraints would be inserted automatically in the generated migrations as well (when running `marten genmigrations`). For example:

```crystal
class Migration::Main::V202211021724301 < Marten::Migration
  def plan
    create_table :main_person do
      column :id, :int, primary_key: true, auto: true
      column :first_name, :string, max_size: 50
      column :last_name, :string, max_size: 50
    
      unique_constraint :author_full_name_constraint, [:first_name, :last_name]
    end
  end
end
```

The mechanism is also available for DB indexes, which can be defined by using the with the [`#db_index`](https://martenframework.com/docs/api/Marten/DB/Model/Table/ClassMethods.html#db_index%28name%3AString%7CSymbol%2Cfield_names%3AArray%28String%29%7CArray%28Symbol%29%29%3ANil-instance-method) class method.

This capacity is not yet documented and this is something that is on my radar. Thanks for raising this! I will let this issue open until this gets added tot the [model documentation](https://martenframework.com/docs/models-and-databases/introduction).

**Comment by jasonl99** [comment]
Awesome, thank you!
