### ISSUE TITLE
marten new project myblog should generate .gitignore file

### ISSUE THREAD

**Issue by carcinocron** [martenframework/marten#49]
It's not clear to me which files the framework author is intending it's users to commit, like the binaries in `tmp/` or `bin/ameba` or `bin/ameba.cr`

**Comment by ellmetha** [comment]
Hey! 👋 This makes sense, and this is indeed something that was missing in the `new` management command. I've added it with 2dcba1a and this will be part of an upcoming bugfix release.

Thanks for flagging this! 🙏
